@TestTaskVitaliyPonomarev_HostAddress = https://localhost:7164

GET {{TestTaskVitaliyPonomarev_HostAddress}}/report/info?queryId=2c729337-1c48-4e50-a140-33fc48bf6409
Content-Type: application/json

###
